// Generated by go-wayland-scanner
// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner
// XML file : internal/inputmethod/protocol/input-method-unstable-v2.xml
//
// zwp_input_method_unstable_v2 Protocol Copyright:
//
// Copyright © 2008-2011 Kristian Høgsberg
// Copyright © 2010-2011 Intel Corporation
// Copyright © 2012-2013 Collabora, Ltd.
// Copyright © 2012, 2013 Intel Corporation
// Copyright © 2015, 2016 Jan Arne Petersen
// Copyright © 2017, 2018 Red Hat, Inc.
// Copyright © 2018 Purism SPC
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package inputmethod

import (
	"github.com/rajveermalviya/go-wayland/wayland/client"
	"golang.org/x/sys/unix"
)

// InputMethod : input method
//
// An input method object allows for clients to compose text.
// The objects connects the client to a text input in an application, and
// lets the client to serve as an input method for a seat.
// The zwp_input_method_v2 object can occupy two distinct states: active and
// inactive. In the active state, the object is associated to and
// communicates with a text input. In the inactive state, there is no
// associated text input, and the only communication is with the compositor.
// Initially, the input method is in the inactive state.
// Requests issued in the inactive state must be accepted by the compositor.
// Because of the serial mechanism, and the state reset on activate event,
// they will not have any effect on the state of the next text input.
// There must be no more than one input method object per seat.
type InputMethod struct {
	client.BaseProxy
	activateHandler        InputMethodActivateHandlerFunc
	deactivateHandler      InputMethodDeactivateHandlerFunc
	surroundingTextHandler InputMethodSurroundingTextHandlerFunc
	textChangeCauseHandler InputMethodTextChangeCauseHandlerFunc
	contentTypeHandler     InputMethodContentTypeHandlerFunc
	doneHandler            InputMethodDoneHandlerFunc
	unavailableHandler     InputMethodUnavailableHandlerFunc
}

// NewInputMethod : input method
//
// An input method object allows for clients to compose text.
// The objects connects the client to a text input in an application, and
// lets the client to serve as an input method for a seat.
// The zwp_input_method_v2 object can occupy two distinct states: active and
// inactive. In the active state, the object is associated to and
// communicates with a text input. In the inactive state, there is no
// associated text input, and the only communication is with the compositor.
// Initially, the input method is in the inactive state.
// Requests issued in the inactive state must be accepted by the compositor.
// Because of the serial mechanism, and the state reset on activate event,
// they will not have any effect on the state of the next text input.
// There must be no more than one input method object per seat.
func NewInputMethod(ctx *client.Context) *InputMethod {
	zwpInputMethodV2 := &InputMethod{}
	ctx.Register(zwpInputMethodV2)
	return zwpInputMethodV2
}

// CommitString : commit string
//
// Send the commit string text for insertion to the application.
// Inserts a string at current cursor position (see commit event
// sequence). The string to commit could be either just a single
// character after a key press or the result of some composing.
// The argument text is a buffer containing the string to insert. There
// is a maximum length of wayland messages, so text can not be longer
// than 4000 bytes.
// Values set with this event are double-buffered. They must be applied
// and reset to initial on the next zwp_text_input_v3.commit request.
// The initial value of text is an empty string.
func (i *InputMethod) CommitString(text string) error {
	const opcode = 0
	textLen := client.PaddedLen(len(text) + 1)
	_reqBufLen := 8 + (4 + textLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+textLen)], text, textLen)
	l += (4 + textLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetPreeditString : pre-edit string
//
// Send the pre-edit string text to the application text input.
// Place a new composing text (pre-edit) at the current cursor position.
// Any previously set composing text must be removed. Any previously
// existing selected text must be removed. The cursor is moved to a new
// position within the preedit string.
// The argument text is a buffer containing the preedit string. There is
// a maximum length of wayland messages, so text can not be longer than
// 4000 bytes.
// The arguments cursor_begin and cursor_end are counted in bytes relative
// to the beginning of the submitted string buffer. Cursor should be
// hidden by the text input when both are equal to -1.
// cursor_begin indicates the beginning of the cursor. cursor_end
// indicates the end of the cursor. It may be equal or different than
// cursor_begin.
// Values set with this event are double-buffered. They must be applied on
// the next zwp_input_method_v2.commit event.
// The initial value of text is an empty string. The initial value of
// cursor_begin, and cursor_end are both 0.
func (i *InputMethod) SetPreeditString(text string, cursorBegin, cursorEnd int32) error {
	const opcode = 1
	textLen := client.PaddedLen(len(text) + 1)
	_reqBufLen := 8 + (4 + textLen) + 4 + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+textLen)], text, textLen)
	l += (4 + textLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(cursorBegin))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(cursorEnd))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// DeleteSurroundingText : delete text
//
// Remove the surrounding text.
// before_length and after_length are the number of bytes before and
// after the current cursor index (excluding the preedit text) to delete.
// If any preedit text is present, it is replaced with the cursor for
// the purpose of this event. In effect before_length is counted from the
// beginning of preedit text, and after_length from its end (see commit
// event sequence).
// Values set with this event are double-buffered. They must be applied
// and reset to initial on the next zwp_input_method_v2.commit request.
// The initial values of both before_length and after_length are 0.
func (i *InputMethod) DeleteSurroundingText(beforeLength, afterLength uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(beforeLength))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(afterLength))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Commit : apply state
//
// Apply state changes from commit_string, set_preedit_string and
// delete_surrounding_text requests.
// The state relating to these events is double-buffered, and each one
// modifies the pending state. This request replaces the current state
// with the pending state.
// The connected text input is expected to proceed by evaluating the
// changes in the following order:
// 1. Replace existing preedit string with the cursor.
// 2. Delete requested surrounding text.
// 3. Insert commit string with the cursor at its end.
// 4. Calculate surrounding text to send.
// 5. Insert new preedit text in cursor position.
// 6. Place cursor inside preedit text.
// The serial number reflects the last state of the zwp_input_method_v2
// object known to the client. The value of the serial argument must be
// equal to the number of done events already issued by that object. When
// the compositor receives a commit request with a serial different than
// the number of past done events, it must proceed as normal, except it
// should not change the current state of the zwp_input_method_v2 object.
func (i *InputMethod) Commit(serial uint32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetInputPopupSurface : create popup surface
//
// Creates a new zwp_input_popup_surface_v2 object wrapping a given
// surface.
// The surface gets assigned the "input_popup" role. If the surface
// already has an assigned role, the compositor must issue a protocol
// error.
func (i *InputMethod) GetInputPopupSurface(surface *client.Surface) (*InputPopupSurface, error) {
	id := NewInputPopupSurface(i.Context())
	const opcode = 4
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GrabKeyboard : grab hardware keyboard
//
// Allow an input method to receive hardware keyboard input and process
// key events to generate text events (with pre-edit) over the wire.
// This allows input methods which compose multiple key events for
// inputting text like it is done for CJK languages.
// The compositor should send all keyboard events on the seat to the grab
// holder via the returned wl_keyboard object. Nevertheless, the
// compositor may decide not to forward any particular event. The
// compositor must not further process any event after it has been
// forwarded to the grab holder.
// Releasing the resulting wl_keyboard object releases the grab.
func (i *InputMethod) GrabKeyboard() (*InputMethodKeyboardGrab, error) {
	keyboard := NewInputMethodKeyboardGrab(i.Context())
	const opcode = 5
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], keyboard.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return keyboard, err
}

// Destroy : destroy the text input
//
// Destroys the zwp_text_input_v2 object and any associated child
// objects, i.e. zwp_input_popup_surface_v2 and
// zwp_input_method_keyboard_grab_v2.
func (i *InputMethod) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 6
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// InputMethodActivateEvent : input method has been requested
//
// Notification that a text input focused on this seat requested the
// input method to be activated.
// This event serves the purpose of providing the compositor with an
// active input method.
// This event resets all state associated with previous enable, disable,
// surrounding_text, text_change_cause, and content_type events, as well
// as the state associated with set_preedit_string, commit_string, and
// delete_surrounding_text requests. In addition, it marks the
// zwp_input_method_v2 object as active, and makes any existing
// zwp_input_popup_surface_v2 objects visible.
// The surrounding_text, and content_type events must follow before the
// next done event if the text input supports the respective functionality.
// State set with this event is double-buffered. It will get applied on
// the next zwp_input_method_v2.done event, and stay valid until changed.
type InputMethodActivateEvent struct{}
type InputMethodActivateHandlerFunc func(InputMethodActivateEvent)

// SetActivateHandler : sets handler for InputMethodActivateEvent
func (i *InputMethod) SetActivateHandler(f InputMethodActivateHandlerFunc) {
	i.activateHandler = f
}

// InputMethodDeactivateEvent : deactivate event
//
// Notification that no focused text input currently needs an active
// input method on this seat.
// This event marks the zwp_input_method_v2 object as inactive. The
// compositor must make all existing zwp_input_popup_surface_v2 objects
// invisible until the next activate event.
// State set with this event is double-buffered. It will get applied on
// the next zwp_input_method_v2.done event, and stay valid until changed.
type InputMethodDeactivateEvent struct{}
type InputMethodDeactivateHandlerFunc func(InputMethodDeactivateEvent)

// SetDeactivateHandler : sets handler for InputMethodDeactivateEvent
func (i *InputMethod) SetDeactivateHandler(f InputMethodDeactivateHandlerFunc) {
	i.deactivateHandler = f
}

// InputMethodSurroundingTextEvent : surrounding text event
//
// Updates the surrounding plain text around the cursor, excluding the
// preedit text.
// If any preedit text is present, it is replaced with the cursor for
// the purpose of this event.
// The argument text is a buffer containing the preedit string, and must
// include the cursor position, and the complete selection. It should
// contain additional characters before and after these. There is a
// maximum length of wayland messages, so text can not be longer than
// 4000 bytes.
// cursor is the byte offset of the cursor within the text buffer.
// anchor is the byte offset of the selection anchor within the text
// buffer. If there is no selected text, anchor must be the same as
// cursor.
// If this event does not arrive before the first done event, the input
// method may assume that the text input does not support this
// functionality and ignore following surrounding_text events.
// Values set with this event are double-buffered. They will be applied
// and set to initial values on the next zwp_input_method_v2.done event.
// The initial state for affected fields is empty, meaning that the text
// input does not support sending surrounding text. If the empty values
// get applied, subsequent attempts to change them may have no effect.
type InputMethodSurroundingTextEvent struct {
	Text   string
	Cursor uint32
	Anchor uint32
}
type InputMethodSurroundingTextHandlerFunc func(InputMethodSurroundingTextEvent)

// SetSurroundingTextHandler : sets handler for InputMethodSurroundingTextEvent
func (i *InputMethod) SetSurroundingTextHandler(f InputMethodSurroundingTextHandlerFunc) {
	i.surroundingTextHandler = f
}

// InputMethodTextChangeCauseEvent : indicates the cause of surrounding text change
//
// Tells the input method why the text surrounding the cursor changed.
// Whenever the client detects an external change in text, cursor, or
// anchor position, it must issue this request to the compositor. This
// request is intended to give the input method a chance to update the
// preedit text in an appropriate way, e.g. by removing it when the user
// starts typing with a keyboard.
// cause describes the source of the change.
// The value set with this event is double-buffered. It will be applied
// and set to its initial value on the next zwp_input_method_v2.done
// event.
// The initial value of cause is input_method.
type InputMethodTextChangeCauseEvent struct {
	Cause uint32
}
type InputMethodTextChangeCauseHandlerFunc func(InputMethodTextChangeCauseEvent)

// SetTextChangeCauseHandler : sets handler for InputMethodTextChangeCauseEvent
func (i *InputMethod) SetTextChangeCauseHandler(f InputMethodTextChangeCauseHandlerFunc) {
	i.textChangeCauseHandler = f
}

// InputMethodContentTypeEvent : content purpose and hint
//
// Indicates the content type and hint for the current
// zwp_input_method_v2 instance.
// Values set with this event are double-buffered. They will be applied
// on the next zwp_input_method_v2.done event.
// The initial value for hint is none, and the initial value for purpose
// is normal.
type InputMethodContentTypeEvent struct {
	Hint    uint32
	Purpose uint32
}
type InputMethodContentTypeHandlerFunc func(InputMethodContentTypeEvent)

// SetContentTypeHandler : sets handler for InputMethodContentTypeEvent
func (i *InputMethod) SetContentTypeHandler(f InputMethodContentTypeHandlerFunc) {
	i.contentTypeHandler = f
}

// InputMethodDoneEvent : apply state
//
// Atomically applies state changes recently sent to the client.
// The done event establishes and updates the state of the client, and
// must be issued after any changes to apply them.
// Text input state (content purpose, content hint, surrounding text, and
// change cause) is conceptually double-buffered within an input method
// context.
// Events modify the pending state, as opposed to the current state in
// use by the input method. A done event atomically applies all pending
// state, replacing the current state. After done, the new pending state
// is as documented for each related request.
// Events must be applied in the order of arrival.
// Neither current nor pending state are modified unless noted otherwise.
type InputMethodDoneEvent struct{}
type InputMethodDoneHandlerFunc func(InputMethodDoneEvent)

// SetDoneHandler : sets handler for InputMethodDoneEvent
func (i *InputMethod) SetDoneHandler(f InputMethodDoneHandlerFunc) {
	i.doneHandler = f
}

// InputMethodUnavailableEvent : input method unavailable
//
// The input method ceased to be available.
// The compositor must issue this event as the only event on the object if
// there was another input_method object associated with the same seat at
// the time of its creation.
// The compositor must issue this request when the object is no longer
// usable, e.g. due to seat removal.
// The input method context becomes inert and should be destroyed after
// deactivation is handled. Any further requests and events except for
// the destroy request must be ignored.
type InputMethodUnavailableEvent struct{}
type InputMethodUnavailableHandlerFunc func(InputMethodUnavailableEvent)

// SetUnavailableHandler : sets handler for InputMethodUnavailableEvent
func (i *InputMethod) SetUnavailableHandler(f InputMethodUnavailableHandlerFunc) {
	i.unavailableHandler = f
}

func (i *InputMethod) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.activateHandler == nil {
			return
		}
		var e InputMethodActivateEvent

		i.activateHandler(e)
	case 1:
		if i.deactivateHandler == nil {
			return
		}
		var e InputMethodDeactivateEvent

		i.deactivateHandler(e)
	case 2:
		if i.surroundingTextHandler == nil {
			return
		}
		var e InputMethodSurroundingTextEvent
		l := 0
		textLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Text = client.String(data[l : l+textLen])
		l += textLen
		e.Cursor = client.Uint32(data[l : l+4])
		l += 4
		e.Anchor = client.Uint32(data[l : l+4])
		l += 4

		i.surroundingTextHandler(e)
	case 3:
		if i.textChangeCauseHandler == nil {
			return
		}
		var e InputMethodTextChangeCauseEvent
		l := 0
		e.Cause = client.Uint32(data[l : l+4])
		l += 4

		i.textChangeCauseHandler(e)
	case 4:
		if i.contentTypeHandler == nil {
			return
		}
		var e InputMethodContentTypeEvent
		l := 0
		e.Hint = client.Uint32(data[l : l+4])
		l += 4
		e.Purpose = client.Uint32(data[l : l+4])
		l += 4

		i.contentTypeHandler(e)
	case 5:
		if i.doneHandler == nil {
			return
		}
		var e InputMethodDoneEvent

		i.doneHandler(e)
	case 6:
		if i.unavailableHandler == nil {
			return
		}
		var e InputMethodUnavailableEvent

		i.unavailableHandler(e)
	}
}

// InputPopupSurface : popup surface
//
// This interface marks a surface as a popup for interacting with an input
// method.
// The compositor should place it near the active text input area. It must
// be visible if and only if the input method is in the active state.
// The client must not destroy the underlying wl_surface while the
// zwp_input_popup_surface_v2 object exists.
type InputPopupSurface struct {
	client.BaseProxy
}

// NewInputPopupSurface : popup surface
//
// This interface marks a surface as a popup for interacting with an input
// method.
// The compositor should place it near the active text input area. It must
// be visible if and only if the input method is in the active state.
// The client must not destroy the underlying wl_surface while the
// zwp_input_popup_surface_v2 object exists.
func NewInputPopupSurface(ctx *client.Context) *InputPopupSurface {
	zwpInputPopupSurfaceV2 := &InputPopupSurface{}
	ctx.Register(zwpInputPopupSurfaceV2)
	return zwpInputPopupSurfaceV2
}

// TextInputRectangle : set text input area position
//
// Notify about the position of the area of the text input expressed as a
// rectangle in surface local coordinates.
// This is a hint to the input method telling it the relative position of
// the text being entered.
func (i *InputPopupSurface) TextInputRectangle(x, y, width, height int32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy the popup surface
//
// Destroy the wp_input_popup_surface_v2 object.
func (i *InputPopupSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// InputMethodKeyboardGrab : keyboard grab
//
// The zwp_input_method_keyboard_grab_v2 interface represents an exclusive
// grab of the wl_keyboard interface associated with the seat.
type InputMethodKeyboardGrab struct {
	client.BaseProxy
	keymapHandler     InputMethodKeyboardGrabKeymapHandlerFunc
	keyHandler        InputMethodKeyboardGrabKeyHandlerFunc
	modifiersHandler  InputMethodKeyboardGrabModifiersHandlerFunc
	repeatInfoHandler InputMethodKeyboardGrabRepeatInfoHandlerFunc
}

// NewInputMethodKeyboardGrab : keyboard grab
//
// The zwp_input_method_keyboard_grab_v2 interface represents an exclusive
// grab of the wl_keyboard interface associated with the seat.
func NewInputMethodKeyboardGrab(ctx *client.Context) *InputMethodKeyboardGrab {
	zwpInputMethodKeyboardGrabV2 := &InputMethodKeyboardGrab{}
	ctx.Register(zwpInputMethodKeyboardGrabV2)
	return zwpInputMethodKeyboardGrabV2
}

// Release : release the grab
//
// Release the grab.
func (i *InputMethodKeyboardGrab) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// InputMethodKeyboardGrabKeymapEvent : keyboard mapping
//
// This event provides a file descriptor to the client which can be
// memory-mapped to provide a keyboard mapping description.
type InputMethodKeyboardGrabKeymapEvent struct {
	Format uint32
	Fd     int
	Size   uint32
}
type InputMethodKeyboardGrabKeymapHandlerFunc func(InputMethodKeyboardGrabKeymapEvent)

// SetKeymapHandler : sets handler for InputMethodKeyboardGrabKeymapEvent
func (i *InputMethodKeyboardGrab) SetKeymapHandler(f InputMethodKeyboardGrabKeymapHandlerFunc) {
	i.keymapHandler = f
}

// InputMethodKeyboardGrabKeyEvent : key event
//
// A key was pressed or released. The time argument is a timestamp with
// millisecond granularity, with an undefined base.
type InputMethodKeyboardGrabKeyEvent struct {
	Serial uint32
	Time   uint32
	Key    uint32
	State  uint32
}
type InputMethodKeyboardGrabKeyHandlerFunc func(InputMethodKeyboardGrabKeyEvent)

// SetKeyHandler : sets handler for InputMethodKeyboardGrabKeyEvent
func (i *InputMethodKeyboardGrab) SetKeyHandler(f InputMethodKeyboardGrabKeyHandlerFunc) {
	i.keyHandler = f
}

// InputMethodKeyboardGrabModifiersEvent : modifier and group state
//
// Notifies clients that the modifier and/or group state has changed, and
// it should update its local state.
type InputMethodKeyboardGrabModifiersEvent struct {
	Serial        uint32
	ModsDepressed uint32
	ModsLatched   uint32
	ModsLocked    uint32
	Group         uint32
}
type InputMethodKeyboardGrabModifiersHandlerFunc func(InputMethodKeyboardGrabModifiersEvent)

// SetModifiersHandler : sets handler for InputMethodKeyboardGrabModifiersEvent
func (i *InputMethodKeyboardGrab) SetModifiersHandler(f InputMethodKeyboardGrabModifiersHandlerFunc) {
	i.modifiersHandler = f
}

// InputMethodKeyboardGrabRepeatInfoEvent : repeat rate and delay
//
// Informs the client about the keyboard's repeat rate and delay.
// This event is sent as soon as the zwp_input_method_keyboard_grab_v2
// object has been created, and is guaranteed to be received by the
// client before any key press event. Negative values for either rate
// or delay are illegal. A rate of zero will disable any repeating
// (regardless of the value of delay).
// This event can be sent later on as well with a new value if necessary,
// so clients should continue listening for the event past the creation
// of zwp_input_method_keyboard_grab_v2.
type InputMethodKeyboardGrabRepeatInfoEvent struct {
	Rate  int32
	Delay int32
}
type InputMethodKeyboardGrabRepeatInfoHandlerFunc func(InputMethodKeyboardGrabRepeatInfoEvent)

// SetRepeatInfoHandler : sets handler for InputMethodKeyboardGrabRepeatInfoEvent
func (i *InputMethodKeyboardGrab) SetRepeatInfoHandler(f InputMethodKeyboardGrabRepeatInfoHandlerFunc) {
	i.repeatInfoHandler = f
}

func (i *InputMethodKeyboardGrab) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.keymapHandler == nil {
			if fd != -1 {
				unix.Close(fd)
			}
			return
		}
		var e InputMethodKeyboardGrabKeymapEvent
		l := 0
		e.Format = client.Uint32(data[l : l+4])
		l += 4
		e.Fd = fd
		e.Size = client.Uint32(data[l : l+4])
		l += 4

		i.keymapHandler(e)
	case 1:
		if i.keyHandler == nil {
			return
		}
		var e InputMethodKeyboardGrabKeyEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		e.Time = client.Uint32(data[l : l+4])
		l += 4
		e.Key = client.Uint32(data[l : l+4])
		l += 4
		e.State = client.Uint32(data[l : l+4])
		l += 4

		i.keyHandler(e)
	case 2:
		if i.modifiersHandler == nil {
			return
		}
		var e InputMethodKeyboardGrabModifiersEvent
		l := 0
		e.Serial = client.Uint32(data[l : l+4])
		l += 4
		e.ModsDepressed = client.Uint32(data[l : l+4])
		l += 4
		e.ModsLatched = client.Uint32(data[l : l+4])
		l += 4
		e.ModsLocked = client.Uint32(data[l : l+4])
		l += 4
		e.Group = client.Uint32(data[l : l+4])
		l += 4

		i.modifiersHandler(e)
	case 3:
		if i.repeatInfoHandler == nil {
			return
		}
		var e InputMethodKeyboardGrabRepeatInfoEvent
		l := 0
		e.Rate = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Delay = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.repeatInfoHandler(e)
	}
}

// InputMethodManager : input method manager
//
// The input method manager allows the client to become the input method
// on a chosen seat.
// No more than one input method must be associated with any seat at any
// given time.
type InputMethodManager struct {
	client.BaseProxy
}

// NewInputMethodManager : input method manager
//
// The input method manager allows the client to become the input method
// on a chosen seat.
// No more than one input method must be associated with any seat at any
// given time.
func NewInputMethodManager(ctx *client.Context) *InputMethodManager {
	zwpInputMethodManagerV2 := &InputMethodManager{}
	ctx.Register(zwpInputMethodManagerV2)
	return zwpInputMethodManagerV2
}

// GetInputMethod : request an input method object
//
// Request a new input zwp_input_method_v2 object associated with a
// given seat.
func (i *InputMethodManager) GetInputMethod(seat *client.Seat) (*InputMethod, error) {
	inputMethod := NewInputMethod(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], inputMethod.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return inputMethod, err
}

// Destroy : destroy the input method manager
//
// Destroys the zwp_input_method_manager_v2 object.
// The zwp_input_method_v2 objects originating from it remain valid.
func (i *InputMethodManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
