// Package theme provides Material Design 3 color scheme utilities and
// wallpaper integration with matugen.
package theme

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/sonroyaalmerol/snry-shell/internal/state"
)

// MatugenRunner abstracts invoking matugen for testability.
type MatugenRunner interface {
	Run(wallpaperPath string) ([]byte, error)
}

type execMatugen struct{}

func (e execMatugen) Run(wallpaperPath string) ([]byte, error) {
	return exec.Command("matugen", "image", wallpaperPath, "--json", "hex").Output()
}

// NewMatugenRunner returns a MatugenRunner backed by the real binary.
func NewMatugenRunner() MatugenRunner { return execMatugen{} }

// GenerateFromWallpaper runs matugen and returns a ColorScheme.
func GenerateFromWallpaper(runner MatugenRunner, wallpaperPath string) (state.ColorScheme, error) {
	out, err := runner.Run(wallpaperPath)
	if err != nil {
		return state.ColorScheme{}, fmt.Errorf("matugen: %w", err)
	}
	return parseMatugenJSON(out)
}

// WriteCSS renders the full M3 token set as GTK CSS @define-color variables.
func WriteCSS(scheme state.ColorScheme, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(RenderCSS(scheme)), 0o644)
}

// RenderCSS is exported so tests can verify output without touching the filesystem.
func RenderCSS(s state.ColorScheme) string {
	return fmt.Sprintf(
		`/* Auto-generated by snry-shell — do not edit */

/* Primary */
@define-color col_primary %s;
@define-color col_on_primary %s;
@define-color col_primary_container %s;
@define-color col_on_primary_container %s;

/* Secondary */
@define-color col_secondary %s;
@define-color col_on_secondary %s;
@define-color col_secondary_container %s;
@define-color col_on_secondary_container %s;

/* Tertiary */
@define-color col_tertiary %s;
@define-color col_on_tertiary %s;
@define-color col_tertiary_container %s;
@define-color col_on_tertiary_container %s;

/* Error */
@define-color col_error %s;
@define-color col_on_error %s;
@define-color col_error_container %s;
@define-color col_on_error_container %s;

/* Surface */
@define-color col_surface %s;
@define-color col_surface_dim %s;
@define-color col_surface_bright %s;
@define-color col_surface_container %s;
@define-color col_surface_container_low %s;
@define-color col_surface_container_high %s;
@define-color col_surface_container_highest %s;
@define-color col_on_surface %s;
@define-color col_on_surface_variant %s;

/* Background */
@define-color col_background %s;
@define-color col_on_background %s;

/* Outline */
@define-color col_outline %s;
@define-color col_outline_variant %s;

/* Convenience */
@define-color col_subtext %s;
`,
		s.Primary, s.OnPrimary, s.PrimaryContainer, s.OnPrimaryContainer,
		s.Secondary, s.OnSecondary, s.SecondaryContainer, s.OnSecondaryContainer,
		s.Tertiary, s.OnTertiary, s.TertiaryContainer, s.OnTertiaryContainer,
		s.Error, s.OnError, s.ErrorContainer, s.OnErrorContainer,
		s.Surface, s.SurfaceDim, s.SurfaceBright,
		s.SurfaceContainer, s.SurfaceContainerLow, s.SurfaceContainerHigh, s.SurfaceContainerHighest,
		s.OnSurface, s.OnSurfaceVariant,
		s.Background, s.OnBackground,
		s.Outline, s.OutlineVariant,
		s.Subtext,
	)
}

func parseMatugenJSON(data []byte) (state.ColorScheme, error) {
	var out matugenOutput
	if err := json.Unmarshal(data, &out); err != nil {
		return state.ColorScheme{}, fmt.Errorf("parse matugen JSON: %w", err)
	}

	// Use "dark" variant for each color role.
	lookup := func(role string) string {
		if entry, ok := out.Colors[role]; ok {
			return entry.Dark.Color
		}
		return ""
	}

	s := state.ColorScheme{
		Primary:            lookup("primary"),
		OnPrimary:          lookup("on_primary"),
		PrimaryContainer:   lookup("primary_container"),
		OnPrimaryContainer: lookup("on_primary_container"),

		Secondary:            lookup("secondary"),
		OnSecondary:          lookup("on_secondary"),
		SecondaryContainer:   lookup("secondary_container"),
		OnSecondaryContainer: lookup("on_secondary_container"),

		Tertiary:            lookup("tertiary"),
		OnTertiary:          lookup("on_tertiary"),
		TertiaryContainer:   lookup("tertiary_container"),
		OnTertiaryContainer: lookup("on_tertiary_container"),

		Error:            lookup("error"),
		OnError:          lookup("on_error"),
		ErrorContainer:   lookup("error_container"),
		OnErrorContainer: lookup("on_error_container"),

		Surface:                 lookup("surface"),
		SurfaceDim:              lookup("surface_dim"),
		SurfaceBright:           lookup("surface_bright"),
		SurfaceContainer:        lookup("surface_container"),
		SurfaceContainerLow:     lookup("surface_container_low"),
		SurfaceContainerHigh:    lookup("surface_container_high"),
		SurfaceContainerHighest: lookup("surface_container_highest"),
		OnSurface:               lookup("on_surface"),
		OnSurfaceVariant:        lookup("on_surface_variant"),

		Background:   lookup("background"),
		OnBackground: lookup("on_background"),

		Outline:        lookup("outline"),
		OutlineVariant: lookup("outline_variant"),

		Subtext: lookup("on_surface_variant"),
	}

	return s, nil
}
